# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170929_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookCover',
            field=models.ImageField(blank=True, upload_to='bookCovers'),
        ),
    ]
