# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_bookcover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bookCover',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
