# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170929_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bookCover',
            field=models.ImageField(blank=True, default='', upload_to='static/bookCover'),
            preserve_default=False,
        ),
    ]
