# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20170929_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bookCover',
            field=models.FileField(upload_to=''),
        ),
    ]
